import {
  ComponentCategory,
  ComponentDirection,
} from '../models/PayslipComponent.schema';
import {
  PayslipStatus,
  PayslipType,
} from '../models/PaySlip.schema';

export const dummyPayslips: any[] = [
  {
    _id: 'ps1',
    employeeId: 'emp1',
    payrollRunId: 'run_oct_2025',
    type: PayslipType.Regular,
    status: PayslipStatus.Paid,
    periodLabel: 'October 2025',
    periodStart: new Date('2025-10-01'),
    periodEnd: new Date('2025-10-31'),
    processedAt: new Date('2025-10-30'),
    effectiveDate: new Date('2025-10-31'),
    currency: 'EGP',
    baseSalary: 20000,
    allowancesTotal: 3000,
    grossSalary: 23000,
    taxesTotal: 2500,
    insuranceTotal: 1500,
    otherDeductionsTotal: 500,
    employerContributionsTotal: 2000,
    netSalary: 18500,
    components: [
      {
        direction: ComponentDirection.Earning,
        category: ComponentCategory.BaseSalary,
        code: 'BASIC',
        label: 'Basic Salary',
        amount: 20000,
      },
      {
        direction: ComponentDirection.Earning,
        category: ComponentCategory.Allowance,
        code: 'TRANS',
        label: 'Transportation Allowance',
        amount: 2000,
      },
      {
        direction: ComponentDirection.Earning,
        category: ComponentCategory.Bonus,
        code: 'BONUS',
        label: 'Performance Bonus',
        amount: 1000,
      },
      {
        direction: ComponentDirection.Deduction,
        category: ComponentCategory.Tax,
        code: 'TAX',
        label: 'Income Tax',
        amount: 2500,
      },
      {
        direction: ComponentDirection.Deduction,
        category: ComponentCategory.Insurance,
        code: 'INS',
        label: 'Social Insurance',
        amount: 1500,
      },
      {
        direction: ComponentDirection.Deduction,
        category: ComponentCategory.OtherDeduction,
        code: 'LATE',
        label: 'Lateness Penalty',
        amount: 500,
      },
      {
        direction: ComponentDirection.Contribution,
        category: ComponentCategory.EmployerContribution,
        code: 'EMP_INS',
        label: 'Employer Insurance Contribution',
        amount: 2000,
      },
    ],
    pdfUrl: 'https://dummy.hr-system.com/payslips/ps1.pdf',
  },
  {
    _id: 'ps2',
    employeeId: 'emp2',
    payrollRunId: 'run_oct_2025',
    type: PayslipType.Regular,
    status: PayslipStatus.Disputed,
    periodLabel: 'October 2025',
    periodStart: new Date('2025-10-01'),
    periodEnd: new Date('2025-10-31'),
    processedAt: new Date('2025-10-30'),
    effectiveDate: new Date('2025-10-31'),
    currency: 'EGP',
    baseSalary: 15000,
    allowancesTotal: 2000,
    grossSalary: 17000,
    taxesTotal: 2000,
    insuranceTotal: 1200,
    otherDeductionsTotal: 0,
    employerContributionsTotal: 1500,
    netSalary: 13800,
    components: [
      {
        direction: ComponentDirection.Earning,
        category: ComponentCategory.BaseSalary,
        code: 'BASIC',
        label: 'Basic Salary',
        amount: 15000,
      },
      {
        direction: ComponentDirection.Earning,
        category: ComponentCategory.Allowance,
        code: 'MEAL',
        label: 'Meal Allowance',
        amount: 2000,
      },
      {
        direction: ComponentDirection.Deduction,
        category: ComponentCategory.Tax,
        code: 'TAX',
        label: 'Income Tax',
        amount: 2000,
      },
      {
        direction: ComponentDirection.Deduction,
        category: ComponentCategory.Insurance,
        code: 'INS',
        label: 'Social Insurance',
        amount: 1200,
      },
      {
        direction: ComponentDirection.Contribution,
        category: ComponentCategory.EmployerContribution,
        code: 'EMP_INS',
        label: 'Employer Insurance Contribution',
        amount: 1500,
      },
    ],
    pdfUrl: 'https://dummy.hr-system.com/payslips/ps2.pdf',
  },
];

export const dummyExpenseClaims: any[] = [
  {
    _id: 'ec1',
    employeeId: 'emp1',
    amount: 500,
    type: 'travel',
    description: 'Taxi to client meeting',
    receipts: ['https://dummy.hr-system.com/receipts/ec1.png'],
    status: 'Paid_In_Payroll',
    approvedAt: new Date('2025-10-25'),
  },
  {
    _id: 'ec2',
    employeeId: 'emp2',
    amount: 300,
    type: 'meal',
    description: 'Team lunch reimbursement',
    receipts: [],
    status: 'Manager_Approved',
    approvedAt: new Date('2025-10-28'),
  },
];

export const dummyDisputes: any[] = [
  {
    _id: 'd1',
    employeeId: 'emp2',
    category: 'salary',
    description: 'Net salary seems lower than expected for October 2025.',
    status: 'under_review',
    managerComment: 'Investigating with payroll.',
    payrollComment: '',
    resolutionDetails: '',
    resolvedAt: null,
  },
  {
    _id: 'd2',
    employeeId: 'emp1',
    category: 'overtime',
    description: 'Overtime hours for 15th October not reflected.',
    status: 'resolved',
    managerComment: 'Overtime approved and added to next payroll.',
    payrollComment: 'Adjustment scheduled for November run.',
    resolutionDetails: 'Will be reflected as backpay in November payslip.',
    resolvedAt: new Date('2025-10-29'),
  },
];

export const dummyEmployeeCompensations: any[] = [
  {
    _id: 'lc1',
    employeeId: 'emp1',
    leaveType: 'annual',
    days: 5,
    amount: 3500,
    baseSalaryAtCalculation: 20000,
    divisor: 260,
    status: 'paid',
    note: 'Year-end leave encashment.',
  },
  {
    _id: 'lc2',
    employeeId: 'emp2',
    leaveType: 'sick',
    days: 2,
    amount: 800,
    baseSalaryAtCalculation: 15000,
    divisor: 260,
    status: 'approved',
    note: 'Sick leave encashment.',
  },
];

export const dummyEmployeeSalaries: any[] = [
  {
    _id: 'sal1',
    employeeId: 'emp1',
    salary: 20000,
    ContractType: 'ct_full_time',
  },
  {
    _id: 'sal2',
    employeeId: 'emp2',
    salary: 15000,
    ContractType: 'ct_part_time',
  },
];
